### ISSUE TITLE
Failed at the liveapi@0.0.3 prestart script.

### ISSUE THREAD

**Issue by Luckygirlllll** [Live-API/LAPI-Server#24]
Got error: "`Failed at the liveapi@0.0.3 prestart script.`"  while running command "`sudo curl -s https://raw.githubusercontent.com/live-API/LAPI-Server/master/bin/pull.sh | bash -s"`

Full error: 

```
sh: mongod: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! liveapi@0.0.3 prestart: `pgrep mongod || (mkdir -p db/data && mkdir -p db/logs && mongod --dbpath db/data --fork --logpath db/logs/mongodb.log)`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the liveapi@0.0.3 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`Here is information from the log: `

 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle liveapi@0.0.3~prestart: liveapi@0.0.3
6 verbose lifecycle liveapi@0.0.3~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle liveapi@0.0.3~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Iryna/las/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle liveapi@0.0.3~prestart: CWD: /Users/Iryna/las
9 silly lifecycle liveapi@0.0.3~prestart: Args: [ '-c',
9 silly lifecycle   'pgrep mongod || (mkdir -p db/data && mkdir -p db/logs && mongod --dbpath db/data --fork --logpath db/logs/mongodb.log)' ]
10 info lifecycle liveapi@0.0.3~prestart: Failed to exec prestart script
11 verbose stack Error: liveapi@0.0.3 prestart: `pgrep mongod || (mkdir -p db/data && mkdir -p db/logs && mongod --dbpath db/data --fork --logpath db/logs/mongodb.log)`
11 verbose stack spawn ENOENT
11 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
11 verbose stack     at emitTwo (events.js:125:13)
11 verbose stack     at ChildProcess.emit (events.js:213:7)
11 verbose stack     at maybeClose (internal/child_process.js:927:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
12 verbose pkgid liveapi@0.0.3
13 verbose cwd /Users/Iryna/las
14 verbose Darwin 16.6.0
15 verbose argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
16 verbose node v8.4.0
17 verbose npm  v5.3.0
18 error file sh
19 error code ELIFECYCLE
20 error errno ENOENT
21 error syscall spawn
22 error liveapi@0.0.3 prestart: `pgrep mongod || (mkdir -p db/data && mkdir -p db/logs && mongod --dbpath db/data --fork --logpath db/logs/mongodb.log)`
22 error spawn ENOENT
23 error Failed at the liveapi@0.0.3 prestart script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]




```

**Comment by beekley** [comment]
What OS are you running? Can you try running `npm run update`? That will run the update branch described in start.sh (similar to running `bin/start.sh -f`).

It looks like the mongo daemon `mongod` is not installed or not added to your PATH and available from the command line. The setup scripts should install MongoDB and do this for you though.

**Comment by Luckygirlllll** [comment]
When I run "npm run update " it gives me an error :  'This is related to npm not being able to find a file.". Current version of npm is 5.3.0.
